/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const ChatIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width="33"
    height="32"
    viewBox="0 0 33 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M27.1667 2.66667H5.83332C4.36666 2.66667 3.17999 3.86667 3.17999 5.33334L3.16666 29.3333L8.49999 24H27.1667C28.6333 24 29.8333 22.8 29.8333 21.3333V5.33334C29.8333 3.86667 28.6333 2.66667 27.1667 2.66667ZM8.49999 12H24.5V14.6667H8.49999V12ZM19.1667 18.6667H8.49999V16H19.1667V18.6667ZM24.5 10.6667H8.49999V8H24.5V10.6667Z"
      fill="white"
    />
  </svg>
);
export default ChatIcon;
