/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const ChatCloseIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width="33"
    height="32"
    viewBox="0 0 33 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_319_595"
      style={{ maskType: 'luminance' }}
      maskUnits="userSpaceOnUse"
      x="2"
      y="1"
      width="29"
      height="30"
    >
      <path
        d="M4.5 26V5.33333C4.5 4.6 5.1 4 5.83333 4H27.1667C27.9 4 28.5 4.6 28.5 5.33333V21.3333C28.5 22.0667 27.9 22.6667 27.1667 22.6667H7.83333L4.5 26Z"
        fill="white"
        fillOpacity="0.3"
        stroke="white"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M11.1666 9.33333H21.8333"
        stroke="white"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M11.1666 13.3333H21.8333"
        stroke="white"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M11.1666 17.3333H16.5"
        stroke="white"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M5.18628 2.80067L29.6993 27.3137"
        stroke="black"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        d="M3.30066 4.68629L27.8137 29.1993"
        stroke="white"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </mask>
    <g mask="url(#mask0_319_595)">
      <path d="M32.5 0H0.5V32H32.5V0Z" fill="white" />
    </g>
  </svg>
);
export default ChatCloseIcon;
